Repository hanghae99-Challenge-2-teams/NETicket, pull requests merged in 2023-05, with the labels that each got.

#100 Dev <- Feature/gy
  build.gradle
  src/main/java/com/example/neticket/config/RedisConfig.java
  src/main/java/com/example/neticket/event/repository/TicketInfoRepository.java
  src/main/java/com/example/neticket/event/service/TicketInfoService.java
  src/main/java/com/example/neticket/reservation/repository/ReservationRepository.java
  src/main/java/com/example/neticket/reservation/service/ReservationService.java
  src/main/java/com/example/neticket/security/UserDetailsServiceImpl.java
Labels: enhancement

#104 Dev <- Feature/gy
  src/main/java/com/example/neticket/event/entity/TicketInfo.java
  src/main/java/com/example/neticket/event/repository/TicketInfoRepository.java
  src/main/java/com/example/neticket/reservation/service/ReservationService.java
  src/main/java/com/example/neticket/security/UserDetailsServiceImpl.java
  src/test/java/com/example/neticket/reservation/service/ReservationServiceTest.java
Labels: enhancement

#105 main<- Dev
  src/main/java/com/example/neticket/event/entity/TicketInfo.java
  src/main/java/com/example/neticket/event/repository/TicketInfoRepository.java
  src/main/java/com/example/neticket/reservation/service/ReservationService.java
  src/main/java/com/example/neticket/security/UserDetailsServiceImpl.java
  src/test/java/com/example/neticket/reservation/service/ReservationServiceTest.java
Labels: enhancement

#106 Fix : docker build arm64 변경
  .github/workflows/gradle.yml
  src/main/java/com/example/neticket/security/UserDetailsServiceImpl.java
Labels: bug

#107 dev <- main
  .github/workflows/gradle.yml
Labels: bug

#109 Feature/yujin
  build.gradle
  src/main/java/com/example/neticket/config/QueryDSLConfig.java
  src/main/java/com/example/neticket/config/RedisConfig.java
  src/main/java/com/example/neticket/event/repository/EventRepository.java
  src/main/java/com/example/neticket/event/repository/EventRepositoryCustom.java
  src/main/java/com/example/neticket/event/repository/EventRepositoryImpl.java
  src/main/java/com/example/neticket/jwt/JwtUtil.java
  src/main/java/com/example/neticket/user/service/UserService.java
  src/main/resources/static/css/style.css
  src/main/resources/static/js/basic.js
  src/main/resources/templates/addevent.html
  src/main/resources/templates/completed.html
  src/main/resources/templates/detail.html
  src/main/resources/templates/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/navbar.html
  src/main/resources/templates/reservation.html
  src/main/resources/templates/search.html
  src/test/java/com/example/neticket/user/service/UserServiceTest.java
Labels: enhancement

#110 Dev
  build.gradle
  src/main/java/com/example/neticket/config/QueryDSLConfig.java
  src/main/java/com/example/neticket/config/RedisConfig.java
  src/main/java/com/example/neticket/event/repository/EventRepository.java
  src/main/java/com/example/neticket/event/repository/EventRepositoryCustom.java
  src/main/java/com/example/neticket/event/repository/EventRepositoryImpl.java
  src/main/java/com/example/neticket/jwt/JwtUtil.java
  src/main/java/com/example/neticket/user/service/UserService.java
  src/main/resources/static/css/style.css
  src/main/resources/static/js/basic.js
  src/main/resources/templates/addevent.html
  src/main/resources/templates/completed.html
  src/main/resources/templates/detail.html
  src/main/resources/templates/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/navbar.html
  src/main/resources/templates/reservation.html
  src/main/resources/templates/search.html
  src/test/java/com/example/neticket/user/service/UserServiceTest.java
Labels: enhancement

#112 Main <- Dev
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/com/example/neticket/config/CacheConfig.java
  src/main/java/com/example/neticket/config/QueryDSLConfig.java
  src/main/java/com/example/neticket/config/ResponseTimeAop.java
  src/main/java/com/example/neticket/event/controller/EventController.java
  src/main/java/com/example/neticket/event/repository/EventRepository.java
  src/main/java/com/example/neticket/event/repository/TicketInfoRepository.java
  src/main/java/com/example/neticket/event/service/TicketInfoService.java
  src/main/java/com/example/neticket/reservation/service/ReservationService.java
  src/main/java/com/example/neticket/security/UserDetailsServiceImpl.java
  src/main/java/com/example/neticket/user/controller/UserController.java
  src/main/resources/import.sql
  src/test/java/com/example/neticket/event/service/EventServiceTest.java
  src/test/java/com/example/neticket/event/service/addEventServiceTest.java
  src/test/java/com/example/neticket/reservation/service/ReservationServiceTest.java
  src/test/java/com/example/neticket/user/service/UserServiceTest.java
Labels: bug

#113 Fix : 예매하기 로직 롤백
  src/main/java/com/example/neticket/reservation/service/ReservationService.java
  src/test/java/com/example/neticket/reservation/service/ReservationServiceTest.java
Labels: bug

#115 Dev <- Feature/yujin
  src/main/resources/static/css/style.css
  src/main/resources/static/js/basic.js
  src/main/resources/templates/addevent.html
  src/main/resources/templates/completed.html
  src/main/resources/templates/footer.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/navbar.html
  src/main/resources/templates/search.html
  src/main/resources/templates/signup.html
Labels: enhancement

#117 Dev <- Feature/yujin
  src/main/resources/static/js/basic.js
  src/main/resources/templates/index.html
Labels: documentation

#118 main <- Dev
  src/main/resources/static/js/basic.js
  src/main/resources/templates/index.html
Labels: documentation

#120 Feat : 공연 데이터 50개 추가, 상세페이지 예매종료 표시
  src/main/resources/import.sql
  src/main/resources/static/js/basic.js
  src/main/resources/templates/detail.html
Labels: enhancement

#121 Update README.md
  README.md
Labels: documentation

#123 Fix : 티켓 예매 종료 오류 수정
  src/main/java/com/example/neticket/event/service/TicketInfoService.java
  src/main/java/com/example/neticket/reservation/repository/RedisRepository.java
Labels: bug
