Repository hanghae99-Challenge-2-teams/NETicket, pull requests merged in 2023-04, with the labels that each got.

#17 Feat : 메인페이지 index.html 추가
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
Labels: enhancement

#23 Fix : 로그인페이지 시큐리티 설정에서 (resource/**) 제외 추가로 로그인 오류 해결
  src/main/java/com/example/neticket/config/WebSecurityConfig.java
  src/main/java/com/example/neticket/user/controller/UserController.java
  src/main/resources/static/css/stylejang.css
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
Labels: bug

#24 Fix : login.html 회원가입 버튼 오타 수정
  src/main/resources/templates/login.html
Labels: bug

#27 Feat : mypage.html 내가 예매한 공연만 조회구현까지 완료
  src/main/java/com/example/neticket/config/WebSecurityConfig.java
  src/main/java/com/example/neticket/connection/PageController.java
  src/main/resources/import.sql
  src/main/resources/templates/mypage.html
  src/main/resources/templates/reservation.html
Labels: enhancement

#43 LockAcquisitionException 오류 해결
  src/main/java/com/example/neticket/event/entity/TicketInfo.java
  src/main/java/com/example/neticket/event/repository/TicketInfoRepository.java
  src/main/java/com/example/neticket/reservation/service/ReservationService.java
  src/main/resources/import.sql
Labels: bug

#46 Fix : html $(document).ready(function () 이동
  src/main/java/com/example/neticket/event/dto/TicketInfoResponseDto.java
  src/main/java/com/example/neticket/event/entity/Event.java
  src/main/java/com/example/neticket/event/entity/TicketInfo.java
  src/main/java/com/example/neticket/reservation/service/ReservationService.java
  src/main/java/com/example/neticket/user/entity/User.java
  src/main/resources/import.sql
  src/main/resources/static/js/basic.js
  src/main/resources/templates/completed.html
  src/main/resources/templates/detail.html
  src/main/resources/templates/index.html
  src/main/resources/templates/reservation.html
Labels: bug

#50 feat : 공연추가기능 구현 완료
  src/main/java/com/example/neticket/config/S3Config.java
  src/main/java/com/example/neticket/event/controller/EventController.java
  src/main/java/com/example/neticket/event/dto/DetailEventResponseDto.java
  src/main/java/com/example/neticket/event/dto/EventRequestDto.java
  src/main/java/com/example/neticket/event/dto/EventResponseDto.java
  src/main/java/com/example/neticket/event/entity/Event.java
  src/main/java/com/example/neticket/event/entity/TicketInfo.java
  src/main/java/com/example/neticket/event/service/EventService.java
  src/main/java/com/example/neticket/reservation/controller/ReservationController.java
  src/main/java/com/example/neticket/reservation/service/ReservationService.java
  src/main/resources/import.sql
Labels: enhancement

#57 Refactor : 공연 삭제 기능 주석처리
  src/main/java/com/example/neticket/event/controller/EventController.java
  src/main/java/com/example/neticket/event/service/EventService.java
  src/main/java/com/example/neticket/user/controller/UserController.java
  src/main/java/com/example/neticket/user/dto/LoginResponseDto.java
  src/main/java/com/example/neticket/user/service/UserService.java
  src/main/resources/static/js/basic.js
  src/main/resources/templates/detail.html
  src/main/resources/templates/mypage.html
Labels: enhancement

#58 Refactor : 같이 코드 리뷰 후 수정
  src/main/java/com/example/neticket/connection/PageController.java
  src/main/java/com/example/neticket/exception/GlobalExceptionHandler.java
  src/main/java/com/example/neticket/reservation/service/ReservationService.java
  src/main/resources/static/js/basic.js
  src/main/resources/templates/completed.html
  src/main/resources/templates/detail.html
  src/main/resources/templates/index.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/reservation.html
  src/main/resources/templates/signup.html
Labels: enhancement

#61 Test : 메인페이지, 상세페이지 TestCode
  src/test/java/com/example/neticket/event/service/EventServiceTest.java
Labels: enhancement

#63 Fix : Type definition error 수정
  src/main/java/com/example/neticket/event/dto/EventRequestDto.java
  src/main/java/com/example/neticket/reservation/dto/ReservationRequestDto.java
  src/main/java/com/example/neticket/reservation/dto/ReservationResponseDto.java
  src/main/java/com/example/neticket/user/dto/SignupRequestDto.java
Labels: bug

#65 Feature/#64redis jang
  src/main/java/com/example/neticket/config/RedisConfig.java
  src/main/java/com/example/neticket/event/dto/DetailEventResponseDto.java
  src/main/java/com/example/neticket/event/dto/TicketInfoResponseDto.java
  src/main/java/com/example/neticket/event/service/EventService.java
  src/main/java/com/example/neticket/reservation/service/ReservationService.java
  src/main/resources/static/js/basic.js
  src/main/resources/templates/addevent.html
  src/main/resources/templates/completed.html
  src/main/resources/templates/detail.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/reservation.html
Labels: enhancement

#66 Dev<-Feature/#64redis
  build.gradle
  src/main/java/com/example/neticket/config/RedisConfig.java
  src/main/java/com/example/neticket/event/dto/DetailEventResponseDto.java
  src/main/java/com/example/neticket/event/dto/TicketInfoResponseDto.java
  src/main/java/com/example/neticket/event/entity/TicketInfo.java
  src/main/java/com/example/neticket/event/service/EventService.java
  src/main/java/com/example/neticket/reservation/controller/ReservationController.java
  src/main/java/com/example/neticket/reservation/dto/ReservationResponseDto.java
  src/main/java/com/example/neticket/reservation/entity/Reservation.java
  src/main/java/com/example/neticket/reservation/repository/RedisRepository.java
  src/main/java/com/example/neticket/reservation/service/ReservationService.java
  src/main/java/com/example/neticket/user/service/UserService.java
  src/main/resources/static/js/basic.js
  src/main/resources/templates/addevent.html
  src/main/resources/templates/completed.html
  src/main/resources/templates/detail.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/reservation.html
  src/test/java/com/example/neticket/event/service/EventServiceTest.java
Labels: enhancement

#67 Feat : LeftSeats Refresh 기능 추가
  src/main/java/com/example/neticket/exception/ExceptionType.java
  src/main/java/com/example/neticket/reservation/controller/ReservationController.java
  src/main/java/com/example/neticket/reservation/repository/RedisRepository.java
  src/main/java/com/example/neticket/reservation/repository/ReservationRepository.java
  src/main/java/com/example/neticket/reservation/service/ReservationService.java
Labels: enhancement

#68 Feat: 프론트 관리자페이지에 갱신과 list 반영
  src/main/java/com/example/neticket/reservation/repository/RedisRepository.java
  src/main/resources/static/js/basic.js
  src/main/resources/templates/addevent.html
Labels: enhancement

#72 Fix : 캐시 사용시 남은 좌석 수 음수 문제 해결
  src/main/java/com/example/neticket/reservation/repository/RedisRepository.java
  src/main/java/com/example/neticket/reservation/service/ReservationService.java
Labels: enhancement

#74 dev <- Feature/redis lock
  src/main/java/com/example/neticket/config/ResponseTimeAop.java
  src/main/java/com/example/neticket/reservation/controller/ReservationController.java
  src/main/java/com/example/neticket/reservation/service/ReservationService.java
  src/main/java/com/example/neticket/user/controller/AdminController.java
  src/main/java/com/example/neticket/user/service/AdminService.java
  src/main/resources/static/js/basic.js
  src/main/resources/templates/completed.html
Labels: enhancement

#79 Main <- Dev
  .gitignore
  build.gradle
  src/main/java/com/example/neticket/config/RedisConfig.java
  src/main/java/com/example/neticket/config/ResponseTimeAop.java
  src/main/java/com/example/neticket/event/dto/DetailEventResponseDto.java
  src/main/java/com/example/neticket/event/dto/EventRequestDto.java
  src/main/java/com/example/neticket/event/dto/TicketInfoResponseDto.java
  src/main/java/com/example/neticket/event/entity/TicketInfo.java
  src/main/java/com/example/neticket/event/service/EventService.java
  src/main/java/com/example/neticket/exception/ExceptionType.java
  src/main/java/com/example/neticket/reservation/controller/ReservationController.java
  src/main/java/com/example/neticket/reservation/dto/ReservationRequestDto.java
  src/main/java/com/example/neticket/reservation/dto/ReservationResponseDto.java
  src/main/java/com/example/neticket/reservation/entity/Reservation.java
  src/main/java/com/example/neticket/reservation/repository/RedisRepository.java
  src/main/java/com/example/neticket/reservation/repository/ReservationRepository.java
  src/main/java/com/example/neticket/reservation/service/ReservationService.java
  src/main/java/com/example/neticket/user/controller/AdminController.java
  src/main/java/com/example/neticket/user/dto/SignupRequestDto.java
  src/main/java/com/example/neticket/user/service/AdminService.java
  src/main/java/com/example/neticket/user/service/UserService.java
  src/main/resources/import.sql
  src/main/resources/static/css/style.css
  src/main/resources/static/images/category.png
  src/main/resources/static/images/logo.png
  src/main/resources/static/images/logo2.png
  src/main/resources/static/js/basic.js
  src/main/resources/templates/addevent.html
  src/main/resources/templates/completed.html
  src/main/resources/templates/detail.html
  src/main/resources/templates/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/navbar.html
  src/main/resources/templates/reservation.html
  src/main/resources/templates/signup.html
  src/test/java/com/example/neticket/event/service/EventServiceTest.java
Labels: enhancement

#81 Dev <- Fix/jang cache
  src/main/java/com/example/neticket/event/repository/TicketInfoRepository.java
  src/main/java/com/example/neticket/event/service/TicketInfoService.java
  src/main/java/com/example/neticket/reservation/repository/RedisRepository.java
  src/main/java/com/example/neticket/user/controller/AdminController.java
  src/main/java/com/example/neticket/user/service/AdminService.java
  src/main/resources/import.sql
  src/main/resources/static/js/basic.js
  src/main/resources/templates/addevent.html
Labels: enhancement

#84 Dev <- Feature/gy
  src/main/java/com/example/neticket/config/ResponseTimeAop.java
  src/main/java/com/example/neticket/connection/PageController.java
  src/main/java/com/example/neticket/event/controller/EventController.java
  src/main/java/com/example/neticket/event/dto/EventResponseDto.java
  src/main/java/com/example/neticket/event/repository/EventRepository.java
  src/main/java/com/example/neticket/event/service/EventService.java
  src/main/java/com/example/neticket/exception/ExceptionType.java
  src/main/resources/import.sql
  src/main/resources/static/js/basic.js
  src/main/resources/templates/navbar.html
  src/main/resources/templates/search.html
Labels: enhancement

#86 Main <- Dev
  src/main/java/com/example/neticket/config/ResponseTimeAop.java
  src/main/java/com/example/neticket/connection/PageController.java
  src/main/java/com/example/neticket/event/controller/EventController.java
  src/main/java/com/example/neticket/event/dto/EventResponseDto.java
  src/main/java/com/example/neticket/event/repository/EventRepository.java
  src/main/java/com/example/neticket/event/repository/TicketInfoRepository.java
  src/main/java/com/example/neticket/event/service/EventService.java
  src/main/java/com/example/neticket/event/service/TicketInfoService.java
  src/main/java/com/example/neticket/exception/ExceptionType.java
  src/main/java/com/example/neticket/reservation/repository/RedisRepository.java
  src/main/java/com/example/neticket/user/controller/AdminController.java
  src/main/java/com/example/neticket/user/service/AdminService.java
  src/main/resources/import.sql
  src/main/resources/static/js/basic.js
  src/main/resources/templates/addevent.html
  src/main/resources/templates/navbar.html
  src/main/resources/templates/search.html
Labels: bug, enhancement

#87 dev <- Feature/yujin
  .github/workflows/gradle.yml
  Dockerfile
  README.md
  appspec.yml
  build.gradle
  scripts/start.sh
  scripts/stop.sh
  src/main/resources/static/js/basic.js
Labels: enhancement

#89 Feat : UserDetailsImpl 수정
  src/main/java/com/example/neticket/config/RedisConfig.java
  src/main/java/com/example/neticket/jwt/JwtUtil.java
  src/main/java/com/example/neticket/security/UserDetailsServiceImpl.java
Labels: enhancement

#91 main <- Dev
  src/main/java/com/example/neticket/config/RedisConfig.java
  src/main/java/com/example/neticket/event/service/TicketInfoService.java
  src/main/java/com/example/neticket/jwt/JwtUtil.java
  src/main/java/com/example/neticket/security/UserDetailsServiceImpl.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/addevent.html
  src/main/resources/templates/index.html
  src/main/resources/templates/signup.html
Labels: enhancement

#92 Main <- Dev
  build.gradle
  src/main/java/com/example/neticket/config/RedisConfig.java
  src/main/java/com/example/neticket/config/WebSecurityConfig.java
  src/main/java/com/example/neticket/connection/PageController.java
  src/main/java/com/example/neticket/event/controller/EventController.java
  src/main/java/com/example/neticket/event/dto/DetailEventResponseDto.java
  src/main/java/com/example/neticket/event/dto/EventRequestDto.java
  src/main/java/com/example/neticket/event/dto/EventResponseDto.java
  src/main/java/com/example/neticket/event/dto/TicketInfoResponseDto.java
  src/main/java/com/example/neticket/event/entity/Event.java
  src/main/java/com/example/neticket/event/entity/TicketInfo.java
  src/main/java/com/example/neticket/event/repository/EventRepository.java
  src/main/java/com/example/neticket/event/repository/TicketInfoRepository.java
  src/main/java/com/example/neticket/event/service/EventService.java
  src/main/java/com/example/neticket/event/service/TicketInfoService.java
  src/main/java/com/example/neticket/exception/CustomException.java
  src/main/java/com/example/neticket/exception/ExceptionHandlerFilter.java
  src/main/java/com/example/neticket/exception/GlobalExceptionHandler.java
  src/main/java/com/example/neticket/jwt/JwtAuthFilter.java
  src/main/java/com/example/neticket/jwt/JwtUtil.java
  src/main/java/com/example/neticket/reservation/controller/ReservationController.java
  src/main/java/com/example/neticket/reservation/dto/ReservationRequestDto.java
  src/main/java/com/example/neticket/reservation/dto/ReservationResponseDto.java
  src/main/java/com/example/neticket/reservation/entity/Reservation.java
  src/main/java/com/example/neticket/reservation/entity/Timestamped.java
  src/main/java/com/example/neticket/reservation/repository/RedisRepository.java
  src/main/java/com/example/neticket/reservation/repository/ReservationRepository.java
  src/main/java/com/example/neticket/reservation/service/ReservationService.java
  src/main/java/com/example/neticket/security/UserDetailsImpl.java
  src/main/java/com/example/neticket/security/UserDetailsServiceImpl.java
  src/main/java/com/example/neticket/user/controller/AdminController.java
  src/main/java/com/example/neticket/user/controller/UserController.java
  src/main/java/com/example/neticket/user/dto/LoginResponseDto.java
  src/main/java/com/example/neticket/user/dto/SignupRequestDto.java
  src/main/java/com/example/neticket/user/entity/User.java
  src/main/java/com/example/neticket/user/entity/UserRoleEnum.java
  src/main/java/com/example/neticket/user/repository/UserRepository.java
  src/main/java/com/example/neticket/user/service/AdminService.java
  src/main/java/com/example/neticket/user/service/UserService.java
  src/main/resources/import.sql
Labels: enhancement

#93 Fix : 양방향 매핑 설정
  src/main/java/com/example/neticket/event/entity/Event.java
  src/main/java/com/example/neticket/event/entity/TicketInfo.java
Labels: bug

#94 Feature/hyeok1
  src/main/resources/templates/reservation.html
  src/main/resources/templates/signup.html
Labels: enhancement

#95 Dev <- Feature/gy
  src/main/java/com/example/neticket/event/entity/TicketInfo.java
  src/main/java/com/example/neticket/reservation/dto/ReservationResponseDto.java
  src/main/java/com/example/neticket/reservation/entity/Reservation.java
  src/main/java/com/example/neticket/reservation/entity/Timestamped.java
  src/main/java/com/example/neticket/reservation/service/ReservationService.java
  src/test/java/com/example/neticket/reservation/service/ReservationServiceTest.java
Labels: enhancement
